# =====================================================
# AstralisEssen — Конфигурационный файл
# Автор: Astralis Team
# Версия: 1.0.0
# =====================================================

# Плейсхолдеры
# {player}     — ник игрока, которого коснулось действие
# {moderator}  — ник модератора, кто выдал наказание
# {time}       — время действия наказания (или "permanent")
# {reason}     — причина наказания
# {date}       — дата окончания наказания

logs:
  enabled: true
  path: "plugins/AstralisEssen/logs"

chat:
  prefix: "§8[<b><gradient:#96C612:#1DD965>ᴇꜱꜱᴇɴ</gradient></b>&7] §7"

# =====================================================
# ВАРНЫ
# =====================================================
warn:
  duration: 1h
  message: "&e{player} получил предупреждение от {moderator}: &7{reason}"
  remove-message: "&aВарн с {player} истёк."

warn-limit:
  count: 3
  actions:
    - "ban {player} 30d 3 предупреждения"

join-quit:
  enable: true
  join: "&bДобро пожаловать на сервер &f%player%&b!"
  quit: "&c%player% &7вышел с сервера."

# =====================================================
# ОСНОВНЫЕ СООБЩЕНИЯ
# =====================================================
messages:
  config-reload: "&aКонфиг AstralisEssen успешно перезагружен!"

  # БАНЫ
  ban-broadcast: "&c{player} был забанен администратором {moderator} на {time}. Причина: {reason}"
  unban-broadcast: "&a{player} был разбанен администратором {moderator}. Причина: {reason}"

  banip-broadcast: "&4IP-адрес {player} был забанен администратором {moderator} на {time}. Причина: {reason}"
  unbanip-broadcast: "&aIP-адрес {player} был разбанен администратором {moderator}. Причина: {reason}"

  ban-player:
    - "&cВы были забанены!"
    - "&7Модератор: &f{moderator}"
    - "&7Причина: &e{reason}"
    - "&7Разбан через: &c{time}"
    - "&7Дата окончания: &f{date}"
    - "&7Подать апелляцию можно в нашем Discord:"
    - "&bdiscord.gg/yourserver"

  # МУТЫ
  mute-player:
    - "&eВы были замьючены!"
    - "&7Модератор: &f{moderator}"
    - "&7Причина: &e{reason}"
    - "&7Срок: &c{time}"
    - "&7Дата окончания: &f{date}"
    - "&7Вы не сможете писать в чат, пока мут не закончится."

  mute-broadcast: "&e{player} был замьючен администратором {moderator} на {time}. Причина: {reason}"
  unmute-broadcast: "&a{player} был размьючен администратором {moderator}. Причина: {reason}"

  # HEAL / FEED / EC
  heal-self: "&aВы полностью исцелены!"
  heal-other: "&aВы исцелили игрока &e{player}&a!"
  healed-by: "&aВас исцелил &e{moderator}&a!"

  feed-self: "&aВы утолили голод!"
  feed-other: "&aВы накормили игрока &e{player}&a!"
  fed-by: "&aВас накормил &e{moderator}&a!"

  ec-open-self: "&aВы открыли свой эндер-сундук."
  ec-open-other: "&aВы открыли эндер-сундук игрока &e{player}&a!"
  ec-no-perm: "&cУ вас нет прав открыть чужой эндер-сундук!"
  ec-player-not-found: "&cИгрок не найден!"

  # КИК / ТП / INVSEE / SMITE
  kick-broadcast: "&c{player} был кикнут администратором {moderator}. Причина: {reason}"
  kick-message:
    - "&cВас кикнули с сервера!"
    - "&7Модератор: &f{moderator}"
    - "&7Причина: &e{reason}"

  tp-success: "&aВы телепортировались к игроку &e{player}&a."
  tp-to-player: "&aВы телепортировали игрока &e{from}&a к &e{to}&a."
  tp-here: "&aВы телепортировали к себе игрока &e{player}&a."
  tp-not-found: "&cИгрок не найден!"

  invsee-open: "&aВы просматриваете инвентарь игрока &e{player}&a."
  invsee-no-perm: "&cУ вас нет прав смотреть чужие инвентари!"

  smite-struck: "&cВы поразили игрока &e{player}&c молнией!"
  smite-hit: "&cВы были поражены молнией администратором &e{moderator}&c!"

  # ПРОЧЕЕ
  speed-usage: "&cИспользование: /speed <walk/fly> <1-10>"
  speed-invalid: "&cНеверное значение! Введите число от 1 до 10."
  speed-set: "&aСкорость &e{type}&a установлена на &e{value}&a."

  clearchat-success: "&aЧат был очищен администратором &e{moderator}&a."
  clearchat-line: ""

  broadcast-format:
    - "&6&l[Объявление] &7-------------------------------"
    - "&f{message}"
    - "&7Отправил: &b{moderator}"
    - "&6----------------------------------------------"

  ping-self: "&aВаш пинг: &e{ping}мс"
  seen-online: "&aИгрок &e{player}&a сейчас онлайн!"
  seen-offline: "&eИгрок &e{player}&e был в сети: &7{time}"
  seen-unknown: "&cИгрок &e{player}&c ни разу не заходил на сервер."

# =====================================================
# СООБЩЕНИЯ СИСТЕМЫ / ОШИБОК
# =====================================================
command-messages:
  no-permission: "&cУ вас нет прав на использование этой команды!"
  player-only: "&cЭта команда доступна только игрокам!"
  invalid-args: "&cНеверные аргументы. Используйте: %usage%"
  player-not-found: "&cИгрок не найден!"
  success: "&aКоманда выполнена успешно!"
