name: AstralisEssen
main: me.astralis.essen.AstralisEssen
version: 1.0.0
api-version: 1.20
author: Astralis Team
description: Многофункциональный плагин AstralisEssen для серверов Minecraft 1.20.1–1.21.1
website: https://github.com/AstralisTeam

commands:
  essen:
    description: Основная команда AstralisEssen
    usage: /essen reload
    permission: astralis.essen

  fly:
    description: Включает или выключает режим полёта
    usage: /fly
    permission: astralis.fly

  god:
    description: Включает или выключает бессмертие
    usage: /god
    permission: astralis.god

  gm:
    description: Меняет игровой режим (0,1,2,3 или название)
    usage: /gm <0|1|2|3|creative|survival|adventure|spectator>
    permission: astralis.gm

  itemname:
    description: Изменяет название предмета
    usage: /itemname <новое имя>
    permission: astralis.itemname

  itemlore:
    description: Изменяет описание предмета
    usage: /itemlore <новое описание>
    permission: astralis.itemlore

  heal:
    description: Исцеляет игрока
    usage: /heal [игрок]
    permission: astralis.heal

  feed:
    description: Восполняет голод
    usage: /feed [игрок]
    permission: astralis.feed

  ec:
    description: Открывает эндер-сундук
    usage: /ec [игрок]
    permission: astralis.ec

  ban:
    description: Банит игрока на время или навсегда
    usage: /ban <игрок> [время] [причина]
    permission: astralis.ban

  unban:
    description: Разбанивает игрока
    usage: /unban <игрок> [причина]
    permission: astralis.unban

  banip:
    description: Банит IP игрока
    usage: /banip <игрок|ip> [время] [причина]
    permission: astralis.banip

  unbanip:
    description: Разбанивает IP
    usage: /unbanip <ip|игрок> [причина]
    permission: astralis.unbanip

  mute:
    description: Замьючивает игрока
    usage: /mute <игрок> [время] [причина]
    permission: astralis.mute

  unmute:
    description: Снимает мут
    usage: /unmute <игрок> [причина]
    permission: astralis.unmute

  warn:
    description: Выдаёт предупреждение
    usage: /warn <игрок> <причина>
    permission: astralis.warn

  warnings:
    description: Показывает количество предупреждений
    usage: /warnings [игрок]
    permission: astralis.warn

  kick:
    description: Кикает игрока
    usage: /kick <игрок> [причина]
    permission: astralis.kick

  tp:
    description: Телепортирует игрока
    usage: /tp <игрок> [цель]
    permission: astralis.tp

  tphere:
    description: Телепортирует игрока к себе
    usage: /tphere <игрок>
    permission: astralis.tphere

  invsee:
    description: Открывает инвентарь игрока
    usage: /invsee <игрок>
    permission: astralis.invsee

  smite:
    description: Ударяет игрока молнией
    usage: /smite <игрок>
    permission: astralis.smite

  speed:
    description: Меняет скорость ходьбы или полёта
    usage: /speed <walk/fly> <1-10>
    permission: astralis.speed

  clearchat:
    description: Очищает чат
    usage: /clearchat
    permission: astralis.clearchat

  broadcast:
    description: Отправляет глобальное сообщение
    usage: /broadcast <сообщение>
    permission: astralis.broadcast

  ping:
    description: Показывает ваш пинг
    usage: /ping
    permission: astralis.ping

  essreload:
    description: Перезагружает конфиг AstralisEssen
    usage: /essreload
    permission: astralis.essreload

  seen:
    description: Показывает, когда игрок был онлайн
    usage: /seen <игрок>
    permission: astralis.seen

permissions:
  astralis.*:
    description: Доступ ко всем командам AstralisEssen
    children:
      astralis.essen: true
      astralis.fly: true
      astralis.god: true
      astralis.gm: true
      astralis.itemname: true
      astralis.itemlore: true
      astralis.heal: true
      astralis.feed: true
      astralis.ec: true
      astralis.ec.others: true
      astralis.ban: true
      astralis.unban: true
      astralis.banip: true
      astralis.unbanip: true
      astralis.mute: true
      astralis.unmute: true
      astralis.warn: true
      astralis.warnings: true
      astralis.kick: true
      astralis.essreload: true
      astralis.tp: true
      astralis.tphere: true
      astralis.invsee: true
      astralis.smite: true
      astralis.speed: true
      astralis.clearchat: true
      astralis.broadcast: true
      astralis.ping: true
      astralis.seen: true

  astralis.essen:
    description: Позволяет использовать /essen reload
    default: op

  astralis.fly:
    description: Включает/выключает полёт
    default: op

  astralis.god:
    description: Включает/выключает бессмертие
    default: op

  astralis.gm:
    description: Меняет режим игры
    default: op

  astralis.itemname:
    description: Меняет имя предмета
    default: op

  astralis.essreload:
    description: Позволяет использовать /essreload
    default: op

  astralis.itemlore:
    description: Меняет описание предмета
    default: op

  astralis.heal:
    description: Исцеляет себя
    default: op

  astralis.feed:
    description: Восполняет голод
    default: op

  astralis.ec:
    description: Открывает свой эндер-сундук
    default: op

  astralis.ec.others:
    description: Открывает чужой эндер-сундук
    default: op

  astralis.ban:
    description: Банит игроков
    default: op

  astralis.unban:
    description: Разбанивает игроков
    default: op

  astralis.banip:
    description: Банит по IP
    default: op

  astralis.unbanip:
    description: Разбанивает IP
    default: op

  astralis.mute:
    description: Мьютит игроков
    default: op

  astralis.unmute:
    description: Снимает мут
    default: op

  astralis.warn:
    description: Выдаёт предупреждения
    default: op

  astralis.warnings:
    description: Проверяет варны
    default: op

  astralis.kick:
    description: Кикает игроков
    default: op

  astralis.tp:
    description: Телепортирует игроков
    default: op

  astralis.tphere:
    description: Телепортирует к себе
    default: op

  astralis.invsee:
    description: Просматривает инвентари
    default: op

  astralis.smite:
    description: Бьёт молнией
    default: op

  astralis.speed:
    description: Меняет скорость
    default: op

  astralis.clearchat:
    description: Очищает чат
    default: op

  astralis.broadcast:
    description: Делает объявления
    default: op

  astralis.ping:
    description: Проверяет пинг
    default: true

  astralis.seen:
    description: Проверяет, когда игрок был онлайн
    default: op
